export const bestFilms = [
  "The Godfather",
  "Citizen Kane",
  "Casablanca",
  "Gone with the Wind",
  "Lawrence of Arabia",
  "12 Angry Men",
  "Schindler's List",
  "Singin’ in the Rain",
  "Sunset Boulevard",
  "Vertigo",
  "Pulp Fiction",
  "The Shawshank Redemption",
  "Parasite",
  "The Dark Knight",
  "Inception",
  "Fight Club",
  "Forrest Gump",
  "Goodfellas",
  "The Matrix",
  "The Lord of the Rings: The Return of the King",
  "Seven Samurai",
  "Bicycle Thieves",
  "Rashomon",
  "The Seventh Seal",
  "Pan’s Labyrinth",
  "Spirited Away",
  "The Godfather Part II",
  "Star Wars: Episode IV - A New Hope",
  "The Silence of the Lambs",
  "Apocalypse Now",
  "Blade Runner",
  "Amélie",
  "The Grand Budapest Hotel",
  "Back to the Future",
  "Titanic",
  "Whiplash",
  "Django Unchained",
  "The Good, the Bad and the Ugly",
  "Once Upon a Time in the West",
  "One Flew Over the Cuckoo's Nest",
  "The Lion King",
  "Life is Beautiful",
  "Crouching Tiger, Hidden Dragon",
  "Oldboy",
  "The Truman Show",
  "City of God",
  "La La Land",
  "Interstellar",
  "The Green Mile",
  "Joker",
  "Avengers: Endgame",
  "The Social Network",
  "The Wolf of Wall Street",
  "Eternal Sunshine of the Spotless Mind",
  "Alien",
  "Gladiator",
  "Jurassic Park",
  "Mad Max: Fury Road",
  "The Pianist",
  "1917",
  "The Departed",
  "Slumdog Millionaire",
  "Braveheart",
  "Heat",
  "The Big Lebowski",
  "The Usual Suspects",
  "Scarface",
  "Requiem for a Dream",
  "Chinatown",
  "Dr. Strangelove",
  "Saving Private Ryan",
  "A Clockwork Orange",
  "2001: A Space Odyssey",
  "Her",
  "There Will Be Blood",
  "No Country for Old Men",
  "Fargo",
  "Moonlight",
  "The Irishman",
  "The Handmaiden",
  "Portrait of a Lady on Fire",
  "Trainspotting",
  "Bohemian Rhapsody",
  "Room",
  "Call Me by Your Name",
  "Spotlight",
  "The Lives of Others",
  "My Neighbor Totoro",
  "Princess Mononoke",
  "Toy Story",
  "Up",
  "WALL-E",
  "Coco",
  "Ratatouille",
  "Inside Out",
  "Shutter Island",
  "The Prestige",
  "Argo",
  "The Hunt",
  "Dune",
];
